use master
go
if exists (select name from sysdatabases where name='QuanLyChuyenBay')
	drop database QuanLyChuyenBay
go

create database QuanLyChuyenBay
go
USE QuanLyChuyenBay
GO
/****** Object:  Table [dbo].[CHUYENBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHUYENBAY](
	[MACB] [char](4) NOT NULL,
	[SBDI] [char](3) NULL,
	[SBDEN] [char](3) NULL,
	[GIODI] [time](7) NULL,
	[GIODEN] [time](7) NULL,
 CONSTRAINT [PK_ChuyenBay] PRIMARY KEY CLUSTERED 
(
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DATCHO]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DATCHO](
	[MAKH] [char](15) NOT NULL,
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
 CONSTRAINT [PK_DatCho] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC,
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [char](15) NOT NULL,
	[TEN] [nvarchar](15) NULL,
	[DCHI] [nvarchar](50) NULL,
	[DTHOAI] [char](12) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[KHANANG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KHANANG](
	[MANV] [char](15) NOT NULL,
	[MALOAI] [char](15) NOT NULL,
 CONSTRAINT [PK_KHANANG] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LICHBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LICHBAY](
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
	[SOHIEU] [int] NULL,
	[MALOAI] [char](15) NULL,
 CONSTRAINT [PK_LichBay] PRIMARY KEY CLUSTERED 
(
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAIMB]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAIMB](
	[MALOAI] [char](15) NOT NULL,
	[HANGSX] [nchar](15) NULL,
 CONSTRAINT [PK_LoaiMB] PRIMARY KEY CLUSTERED 
(
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MAYBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAYBAY](
	[SOHIEU] [int] NOT NULL,
	[MALOAI] [char](15) NOT NULL,
 CONSTRAINT [PK_MAYBAY] PRIMARY KEY CLUSTERED 
(
	[SOHIEU] ASC,
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](15) NOT NULL,
	[TEN] [nvarchar](15) NULL,
	[DCHI] [nvarchar](50) NULL,
	[DTHOAI] [char](12) NULL,
	[LUONG] [float] NULL,
	[LOAINV] [int] NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHANCONG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHANCONG](
	[MANV] [char](15) NOT NULL,
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
 CONSTRAINT [PK_PhanCong] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'100 ', N'SLC', N'BOS', CAST(0x070040230E430000 AS Time), CAST(0x0700942E7A950000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'112 ', N'DCA', N'DEN', CAST(0x0700B0BD58750000 AS Time), CAST(0x07003A26DA970000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'121 ', N'STL', N'SLC', CAST(0x0700D85EAC3A0000 AS Time), CAST(0x070036D2404D0000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'122 ', N'STL', N'YYV', CAST(0x070074053F470000 AS Time), CAST(0x0700422A79560000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'206 ', N'DFW', N'STL', CAST(0x0700A8E76F4B0000 AS Time), CAST(0x070068F3C9610000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'330 ', N'JKF', N'YYV', CAST(0x070080461C860000 AS Time), CAST(0x0700CE3C479E0000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'334 ', N'ORD', N'MIA', CAST(0x0700E03495640000 AS Time), CAST(0x0700846B4D770000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'335 ', N'MIA', N'ORD', CAST(0x07001882BA7D0000 AS Time), CAST(0x0700BCB872900000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'336 ', N'ORD', N'MIA', CAST(0x070050CFDF960000 AS Time), CAST(0x0700F40598A90000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'337 ', N'MIA', N'ORD', CAST(0x0700543AD4AB0000 AS Time), CAST(0x0700D61230C80000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'394 ', N'DFW', N'MIA', CAST(0x0700B893419F0000 AS Time), CAST(0x0700BCFE35B40000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'395 ', N'MIA', N'DFW', CAST(0x0700881C05B00000 AS Time), CAST(0x07001A72CAC60000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'449 ', N'CDG', N'DEN', CAST(0x070010ACD1530000 AS Time), CAST(0x0700A6B24EA30000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'930 ', N'YYV', N'DCA', CAST(0x070048F9F66C0000 AS Time), CAST(0x07003CE781870000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'931 ', N'DCA', N'YYV', CAST(0x0700E80A7E8E0000 AS Time), CAST(0x07000C7045980000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'932 ', N'DCA', N'YYV', CAST(0x070050CFDF960000 AS Time), CAST(0x07007434A7A00000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'991 ', N'BOS', N'ORD', CAST(0x0700E80A7E8E0000 AS Time), CAST(0x07005497F2990000 AS Time))
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0009           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0009           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0012           ', CAST(0x37250B00 AS Date), N'206 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0045           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0091           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0238           ', CAST(0x37250B00 AS Date), N'334 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0314           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0422           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0582           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0586           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0586           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0613           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0009           ', N'Nga', N'46 Nguyễn Trãi                                  ', N'1313656     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0012           ', N'Hà', N'23 Quang Trung                             ', N'2464032     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0045           ', N'Thu', N'156 Lê Lợi                       ', N'2110213     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0091           ', N'Hải', N'345 Hùng Vương                          ', N'1323232     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0101           ', N'Anh', N'12 Trần Phú                                     ', N'3232323     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0238           ', N'Hy', N'26 Pasteur                                        ', N'5146420     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0314           ', N'Phương', N'456 Võ Văn Tần                               ', N'7964686     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0397           ', N'Thanh', N'234 Lê Văn Sĩ                                     ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0422           ', N'Tiên', N'75 Nguyễn Thông                          ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0582           ', N'Mai', N'798 Nguyễn Du                                    ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0586           ', N'Sơn', N'123 Bạch Đằng                                     ', N'7842135     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0613           ', N'Vũ', N'347 CMT8                                          ', N'9895656     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0934           ', N'Minh           ', N'678 Lê Lai                              ', N'1326213     ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'B727           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'B747           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'DC10           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'A320           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'A340           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'B757           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'DC9            ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1003           ', N'A310           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1003           ', N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'100 ', 11, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'112 ', 11, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'206 ', 13, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'334 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'335 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'337 ', 24, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'449 ', 70, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'100 ', 80, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'112 ', 21, N'DC10           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'206 ', 22, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'334 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'337 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'395 ', 23, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'991 ', 22, N'B757           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x3A250B00 AS Date), N'100 ', 80, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x3B250B00 AS Date), N'100 ', 11, N'B727           ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A310           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A320           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A330           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A340           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B727           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B747           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B757           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'DC10           ', N'MD             ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'DC9            ', N'MD             ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (10, N'B747           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (11, N'B727           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (13, N'B727           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (13, N'B747           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (21, N'DC10           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (21, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (22, N'B757           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (22, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (23, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (24, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (70, N'A310           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (80, N'A310           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (93, N'B757           ')
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1001           ', N'Hương          ', N'8 Điện Biên Phủ', N'0911010020  ', 9000000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1002           ', N'Phong', N'1 Lý Thường Kiệt', N'0123101078  ', 8500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1003           ', N'Quang', N'75 Trương Định', N'0931010033  ', 7500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1004           ', N'Phương', N'354 Lạc Long Quân', N'0901010456  ', 4500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1005           ', N'Giáo', N'65 Nguyễn Thái Sơn', N'0911010334  ', 5500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1006           ', N'Chí', N'12 Nguyễn Kiệm', N'0903330000  ', 5200000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1007           ', N'Tâm', N'36 Nguyễn Văn Cừ', N'0911110022  ', 4500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1008           ', N'Minh', N'182 Cao Lỗ ', N'0901010000  ', 9500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1009           ', N'Nam', N'100 Trần Hưng Đạo', N'0123444054  ', 3000000, 0)
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x3A250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x3B250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1002           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1002           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1003           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1003           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1004           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1004           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1005           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1006           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1006           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x37250B00 AS Date), N'206 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x38250B00 AS Date), N'112 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x38250B00 AS Date), N'991 ')
ALTER TABLE [dbo].[DATCHO]  WITH CHECK ADD  CONSTRAINT [FK_DATCHO_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DATCHO] CHECK CONSTRAINT [FK_DATCHO_KHACHHANG]
GO
ALTER TABLE [dbo].[DATCHO]  WITH CHECK ADD  CONSTRAINT [FK_DATCHO_LICHBAY] FOREIGN KEY([NGAYDI], [MACB])
REFERENCES [dbo].[LICHBAY] ([NGAYDI], [MACB])
GO
ALTER TABLE [dbo].[DATCHO] CHECK CONSTRAINT [FK_DATCHO_LICHBAY]
GO
ALTER TABLE [dbo].[KHANANG]  WITH CHECK ADD  CONSTRAINT [FK_KHANANG_LOAIMB] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAIMB] ([MALOAI])
GO
ALTER TABLE [dbo].[KHANANG] CHECK CONSTRAINT [FK_KHANANG_LOAIMB]
GO
ALTER TABLE [dbo].[KHANANG]  WITH CHECK ADD  CONSTRAINT [FK_KHANANG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[KHANANG] CHECK CONSTRAINT [FK_KHANANG_NHANVIEN]
GO
ALTER TABLE [dbo].[LICHBAY]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAY_CHUYENBAY] FOREIGN KEY([MACB])
REFERENCES [dbo].[CHUYENBAY] ([MACB])
GO
ALTER TABLE [dbo].[LICHBAY] CHECK CONSTRAINT [FK_LICHBAY_CHUYENBAY]
GO
ALTER TABLE [dbo].[LICHBAY]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAY_MAYBAY] FOREIGN KEY([SOHIEU], [MALOAI])
REFERENCES [dbo].[MAYBAY] ([SOHIEU], [MALOAI])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LICHBAY] CHECK CONSTRAINT [FK_LICHBAY_MAYBAY]
GO
ALTER TABLE [dbo].[MAYBAY]  WITH CHECK ADD  CONSTRAINT [FK_MAYBAY_LOAIMB1] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAIMB] ([MALOAI])
GO
ALTER TABLE [dbo].[MAYBAY] CHECK CONSTRAINT [FK_MAYBAY_LOAIMB1]
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_LICHBAY] FOREIGN KEY([NGAYDI], [MACB])
REFERENCES [dbo].[LICHBAY] ([NGAYDI], [MACB])
GO
ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_LICHBAY]
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_NHANVIEN]
GO
ALTER TABLE [dbo].[CHUYENBAY]  WITH CHECK ADD  CONSTRAINT [CK__CHUYENBAY__0EA330E9] CHECK  (([GIODI]<[GIODEN]))
GO
ALTER TABLE [dbo].[CHUYENBAY] CHECK CONSTRAINT [CK__CHUYENBAY__0EA330E9]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD CHECK  (([LOAINV]=(0) OR [LOAINV]=(1)))
GOuse master
go
if exists (select name from sysdatabases where name='QuanLyChuyenBay')
	drop database QuanLyChuyenBay
go

create database QuanLyChuyenBay
go
USE QuanLyChuyenBay
GO
/****** Object:  Table [dbo].[CHUYENBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CHUYENBAY](
	[MACB] [char](4) NOT NULL,
	[SBDI] [char](3) NULL,
	[SBDEN] [char](3) NULL,
	[GIODI] [time](7) NULL,
	[GIODEN] [time](7) NULL,
 CONSTRAINT [PK_ChuyenBay] PRIMARY KEY CLUSTERED 
(
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[DATCHO]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[DATCHO](
	[MAKH] [char](15) NOT NULL,
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
 CONSTRAINT [PK_DatCho] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC,
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [char](15) NOT NULL,
	[TEN] [nvarchar](15) NULL,
	[DCHI] [nvarchar](50) NULL,
	[DTHOAI] [char](12) NULL,
 CONSTRAINT [PK_KHACHHANG] PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[KHANANG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[KHANANG](
	[MANV] [char](15) NOT NULL,
	[MALOAI] [char](15) NOT NULL,
 CONSTRAINT [PK_KHANANG] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LICHBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LICHBAY](
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
	[SOHIEU] [int] NULL,
	[MALOAI] [char](15) NULL,
 CONSTRAINT [PK_LichBay] PRIMARY KEY CLUSTERED 
(
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[LOAIMB]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[LOAIMB](
	[MALOAI] [char](15) NOT NULL,
	[HANGSX] [nchar](15) NULL,
 CONSTRAINT [PK_LoaiMB] PRIMARY KEY CLUSTERED 
(
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[MAYBAY]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[MAYBAY](
	[SOHIEU] [int] NOT NULL,
	[MALOAI] [char](15) NOT NULL,
 CONSTRAINT [PK_MAYBAY] PRIMARY KEY CLUSTERED 
(
	[SOHIEU] ASC,
	[MALOAI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [char](15) NOT NULL,
	[TEN] [nvarchar](15) NULL,
	[DCHI] [nvarchar](50) NULL,
	[DTHOAI] [char](12) NULL,
	[LUONG] [float] NULL,
	[LOAINV] [int] NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PHANCONG]    Script Date: 24/05/2020 10:48:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PHANCONG](
	[MANV] [char](15) NOT NULL,
	[NGAYDI] [date] NOT NULL,
	[MACB] [char](4) NOT NULL,
 CONSTRAINT [PK_PhanCong] PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[NGAYDI] ASC,
	[MACB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'100 ', N'SLC', N'BOS', CAST(0x070040230E430000 AS Time), CAST(0x0700942E7A950000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'112 ', N'DCA', N'DEN', CAST(0x0700B0BD58750000 AS Time), CAST(0x07003A26DA970000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'121 ', N'STL', N'SLC', CAST(0x0700D85EAC3A0000 AS Time), CAST(0x070036D2404D0000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'122 ', N'STL', N'YYV', CAST(0x070074053F470000 AS Time), CAST(0x0700422A79560000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'206 ', N'DFW', N'STL', CAST(0x0700A8E76F4B0000 AS Time), CAST(0x070068F3C9610000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'330 ', N'JKF', N'YYV', CAST(0x070080461C860000 AS Time), CAST(0x0700CE3C479E0000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'334 ', N'ORD', N'MIA', CAST(0x0700E03495640000 AS Time), CAST(0x0700846B4D770000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'335 ', N'MIA', N'ORD', CAST(0x07001882BA7D0000 AS Time), CAST(0x0700BCB872900000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'336 ', N'ORD', N'MIA', CAST(0x070050CFDF960000 AS Time), CAST(0x0700F40598A90000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'337 ', N'MIA', N'ORD', CAST(0x0700543AD4AB0000 AS Time), CAST(0x0700D61230C80000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'394 ', N'DFW', N'MIA', CAST(0x0700B893419F0000 AS Time), CAST(0x0700BCFE35B40000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'395 ', N'MIA', N'DFW', CAST(0x0700881C05B00000 AS Time), CAST(0x07001A72CAC60000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'449 ', N'CDG', N'DEN', CAST(0x070010ACD1530000 AS Time), CAST(0x0700A6B24EA30000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'930 ', N'YYV', N'DCA', CAST(0x070048F9F66C0000 AS Time), CAST(0x07003CE781870000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'931 ', N'DCA', N'YYV', CAST(0x0700E80A7E8E0000 AS Time), CAST(0x07000C7045980000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'932 ', N'DCA', N'YYV', CAST(0x070050CFDF960000 AS Time), CAST(0x07007434A7A00000 AS Time))
INSERT [dbo].[CHUYENBAY] ([MACB], [SBDI], [SBDEN], [GIODI], [GIODEN]) VALUES (N'991 ', N'BOS', N'ORD', CAST(0x0700E80A7E8E0000 AS Time), CAST(0x07005497F2990000 AS Time))
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0009           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0009           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0012           ', CAST(0x37250B00 AS Date), N'206 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0045           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0091           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0238           ', CAST(0x37250B00 AS Date), N'334 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0314           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0422           ', CAST(0x37250B00 AS Date), N'449 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0582           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0586           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0586           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[DATCHO] ([MAKH], [NGAYDI], [MACB]) VALUES (N'0613           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0009           ', N'Nga', N'46 Nguyễn Trãi                                  ', N'1313656     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0012           ', N'Hà', N'23 Quang Trung                             ', N'2464032     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0045           ', N'Thu', N'156 Lê Lợi                       ', N'2110213     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0091           ', N'Hải', N'345 Hùng Vương                          ', N'1323232     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0101           ', N'Anh', N'12 Trần Phú                                     ', N'3232323     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0238           ', N'Hy', N'26 Pasteur                                        ', N'5146420     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0314           ', N'Phương', N'456 Võ Văn Tần                               ', N'7964686     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0397           ', N'Thanh', N'234 Lê Văn Sĩ                                     ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0422           ', N'Tiên', N'75 Nguyễn Thông                          ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0582           ', N'Mai', N'798 Nguyễn Du                                    ', NULL)
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0586           ', N'Sơn', N'123 Bạch Đằng                                     ', N'7842135     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0613           ', N'Vũ', N'347 CMT8                                          ', N'9895656     ')
INSERT [dbo].[KHACHHANG] ([MAKH], [TEN], [DCHI], [DTHOAI]) VALUES (N'0934           ', N'Minh           ', N'678 Lê Lai                              ', N'1326213     ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'B727           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'B747           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1001           ', N'DC10           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'A320           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'A340           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'B757           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1002           ', N'DC9            ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1003           ', N'A310           ')
INSERT [dbo].[KHANANG] ([MANV], [MALOAI]) VALUES (N'1003           ', N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'100 ', 11, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'112 ', 11, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'206 ', 13, N'B727           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'334 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'335 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'337 ', 24, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x37250B00 AS Date), N'449 ', 70, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'100 ', 80, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'112 ', 21, N'DC10           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'206 ', 22, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'334 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'337 ', 10, N'B747           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'395 ', 23, N'DC9            ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x38250B00 AS Date), N'991 ', 22, N'B757           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x3A250B00 AS Date), N'100 ', 80, N'A310           ')
INSERT [dbo].[LICHBAY] ([NGAYDI], [MACB], [SOHIEU], [MALOAI]) VALUES (CAST(0x3B250B00 AS Date), N'100 ', 11, N'B727           ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A310           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A320           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A330           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'A340           ', N'AIRBUS         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B727           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B747           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'B757           ', N'BOEING         ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'DC10           ', N'MD             ')
INSERT [dbo].[LOAIMB] ([MALOAI], [HANGSX]) VALUES (N'DC9            ', N'MD             ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (10, N'B747           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (11, N'B727           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (13, N'B727           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (13, N'B747           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (21, N'DC10           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (21, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (22, N'B757           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (22, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (23, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (24, N'DC9            ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (70, N'A310           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (80, N'A310           ')
INSERT [dbo].[MAYBAY] ([SOHIEU], [MALOAI]) VALUES (93, N'B757           ')
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1001           ', N'Hương          ', N'8 Điện Biên Phủ', N'0911010020  ', 9000000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1002           ', N'Phong', N'1 Lý Thường Kiệt', N'0123101078  ', 8500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1003           ', N'Quang', N'75 Trương Định', N'0931010033  ', 7500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1004           ', N'Phương', N'354 Lạc Long Quân', N'0901010456  ', 4500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1005           ', N'Giáo', N'65 Nguyễn Thái Sơn', N'0911010334  ', 5500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1006           ', N'Chí', N'12 Nguyễn Kiệm', N'0903330000  ', 5200000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1007           ', N'Tâm', N'36 Nguyễn Văn Cừ', N'0911110022  ', 4500000, 0)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1008           ', N'Minh', N'182 Cao Lỗ ', N'0901010000  ', 9500000, 1)
INSERT [dbo].[NHANVIEN] ([MANV], [TEN], [DCHI], [DTHOAI], [LUONG], [LOAINV]) VALUES (N'1009           ', N'Nam', N'100 Trần Hưng Đạo', N'0123444054  ', 3000000, 0)
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x3A250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1001           ', CAST(0x3B250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1002           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1002           ', CAST(0x38250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1003           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1003           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1004           ', CAST(0x37250B00 AS Date), N'100 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1004           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1005           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1006           ', CAST(0x37250B00 AS Date), N'337 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1006           ', CAST(0x38250B00 AS Date), N'991 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x37250B00 AS Date), N'206 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x38250B00 AS Date), N'112 ')
INSERT [dbo].[PHANCONG] ([MANV], [NGAYDI], [MACB]) VALUES (N'1007           ', CAST(0x38250B00 AS Date), N'991 ')
ALTER TABLE [dbo].[DATCHO]  WITH CHECK ADD  CONSTRAINT [FK_DATCHO_KHACHHANG] FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DATCHO] CHECK CONSTRAINT [FK_DATCHO_KHACHHANG]
GO
ALTER TABLE [dbo].[DATCHO]  WITH CHECK ADD  CONSTRAINT [FK_DATCHO_LICHBAY] FOREIGN KEY([NGAYDI], [MACB])
REFERENCES [dbo].[LICHBAY] ([NGAYDI], [MACB])
GO
ALTER TABLE [dbo].[DATCHO] CHECK CONSTRAINT [FK_DATCHO_LICHBAY]
GO
ALTER TABLE [dbo].[KHANANG]  WITH CHECK ADD  CONSTRAINT [FK_KHANANG_LOAIMB] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAIMB] ([MALOAI])
GO
ALTER TABLE [dbo].[KHANANG] CHECK CONSTRAINT [FK_KHANANG_LOAIMB]
GO
ALTER TABLE [dbo].[KHANANG]  WITH CHECK ADD  CONSTRAINT [FK_KHANANG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[KHANANG] CHECK CONSTRAINT [FK_KHANANG_NHANVIEN]
GO
ALTER TABLE [dbo].[LICHBAY]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAY_CHUYENBAY] FOREIGN KEY([MACB])
REFERENCES [dbo].[CHUYENBAY] ([MACB])
GO
ALTER TABLE [dbo].[LICHBAY] CHECK CONSTRAINT [FK_LICHBAY_CHUYENBAY]
GO
ALTER TABLE [dbo].[LICHBAY]  WITH CHECK ADD  CONSTRAINT [FK_LICHBAY_MAYBAY] FOREIGN KEY([SOHIEU], [MALOAI])
REFERENCES [dbo].[MAYBAY] ([SOHIEU], [MALOAI])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LICHBAY] CHECK CONSTRAINT [FK_LICHBAY_MAYBAY]
GO
ALTER TABLE [dbo].[MAYBAY]  WITH CHECK ADD  CONSTRAINT [FK_MAYBAY_LOAIMB1] FOREIGN KEY([MALOAI])
REFERENCES [dbo].[LOAIMB] ([MALOAI])
GO
ALTER TABLE [dbo].[MAYBAY] CHECK CONSTRAINT [FK_MAYBAY_LOAIMB1]
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_LICHBAY] FOREIGN KEY([NGAYDI], [MACB])
REFERENCES [dbo].[LICHBAY] ([NGAYDI], [MACB])
GO
ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_LICHBAY]
GO
ALTER TABLE [dbo].[PHANCONG]  WITH CHECK ADD  CONSTRAINT [FK_PHANCONG_NHANVIEN] FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[PHANCONG] CHECK CONSTRAINT [FK_PHANCONG_NHANVIEN]
GO
ALTER TABLE [dbo].[CHUYENBAY]  WITH CHECK ADD  CONSTRAINT [CK__CHUYENBAY__0EA330E9] CHECK  (([GIODI]<[GIODEN]))
GO
ALTER TABLE [dbo].[CHUYENBAY] CHECK CONSTRAINT [CK__CHUYENBAY__0EA330E9]
GO
ALTER TABLE [dbo].[NHANVIEN]  WITH CHECK ADD CHECK  (([LOAINV]=(0) OR [LOAINV]=(1)))
GO